### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by jalet** [iZettle/javascript-env#27]
With react 15.4 out 'n about, we should probably start working on the next major release.

- [x] Webpack 2
- [x] Hot Reload 3
- [x] React 15.4
- [ ] Speedup webpack compile time

**Comment by janneh** [comment]
![200 1](https://cloud.githubusercontent.com/assets/492335/20523594/1894c8fe-b0b6-11e6-92db-d7cdfacdd31e.gif)

**Comment by janneh** [comment]
We might swap the test reporter with this too... the mocha reporter has served its purpose :) Wish list: concise reporting of successful tests(maybe just dots?), verbose expectation traces on the failed once. Like the once from `expectObservable` should be surfaced.

**Comment by stenehall** [comment]
If this is going to live as an open-source project Version 2.0.0 could maybe be converted into a milestone instead of an Issue?
